name: appinio_video_player
description: A custom video player that builds on top of the official video_player package by flutter and adds many functionalities.
version: 1.4.1
homepage: https://github.com/AmirAslami/rozekhati.git

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  cached_video_player: ^2.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
